# List of common protein tags

PROTEIN_TAGS = {
    "FLAG" : "DYKDDDDK",
    "FLAG variant1" : "DYKDHDI",
    "FLAG variant2" : "DYKDHDG",
    "HA" : "YPYDVPDYA",
    "HA variant" : "YAYDVPDYA",
    "6xHIS" : "HHHHHH",
    "Myc" : "EQKLISEEDL",
    "TEV" : "ENLYFQG",
    "TEV variant" : "ENPYFQG",
    "Myr" : "MGSNKSKPKDASQRR",
    "Myr variant" : "MGSSKSKPKDPSQRA",
    "V5" : "GKPIPNPLLGLDST",
    "TAP" : "GRRIPGLINPWKRRWKKNFIAVSAANRFKKISSSGALDYDIPTTASENLYFQGEFGLAQHDEAVDNKFNKEQQNAFYEILHLPNLNEEQRNAFIQSLKDDPSQSANLLAEAKKLNDAQAPKVDNKFNKEQQNAFYEILHLPNLNEEQRNAFIQSLKDDPSQSANLLAEAKKLNDAQAPKVDANHQ",
    "MBP" : "MKNKLVKFTLTAVAGLVMSSAVMAKMTEGKLVIWINGDKGYNGLAEVGKKFEKDTGISVLVEHPDRLEEKFAQVASTGDGPDIIFWAHDRFGGYAQAGLLTELTPSKEFKDKFVDFAWDAETYNGKVIGYPVAIESLSLIYNKDLVPTPPKSWEEILELDAKLKKDKKNAIMWNLSEPYFTWPIVASNGGYAFKFVNGKYDINDIGVNNEGSQKALQFVVNMVKNKVISADMDYAIAEAAFNKGDAALTINGPWSWGNIEKSKINYGVAVLPTLNGHNAKPFVGVLSAGINSASPNKDLAVEFMENYLLTDDGLETVNKDKPLGAVALKSYQEKLAKDPRIAATMENAKNGEIMPNIAQMSAFWYAEKAAIGNAVSGRQSVKQALDDARARIQKQQ",
}

