# List of common protein tags

PROTEIN_TAGS = (
    ("FLAG","DYKDDDDK"),
    ("FLAG","DYKDHDI"),
    ("FLAG","DYKDHDG"),
    ("HA","YPYDVPDYA"),
    ("VSVG Tag","YTDIEMNRLGK"),
    ("SV40 NLS","PKKKRKV"),
    ("SV40 NLS","PKKKRKVG"),
    ("T7 Tag", "MASMTGGQQMG"),
    ("NLS", "KKRKV"),
    ("6xHIS","HHHHHH"),
    ("Myc","EQKLISEEDL"),
    ("TEV","ENLYFQG"),
    ("TEV","ENPYFQG"),
    ("Myr","MGSNKSKPKDASQRR"),
    ("Myr","MGSSKSKPKDPSQRA"),
    ("V5","GKPIPNPLLGLDST"),
    ("S15","KETAAAKFERQHMDS"),
    ("Strep Tag","WSHPQFEK"),
    ("SBP Tag","MDEKTTGWRGGHVVEGLAGELEQLRARLEHHPQGQREP"),
    ("TAP","GRRIPGLINPWKRRWKKNFIAVSAANRFKKISSSGALDYDIPTTASENLYFQGEFGLAQHDEAVDNKFNKEQQNAFYEILHLPNLNEEQRNAFIQSLKDDPSQSANLLAEAKKLNDAQAPKVDNKFNKEQQNAFYEILHLPNLNEEQRNAFIQSLKDDPSQSANLLAEAKKLNDAQAPKVDANHQ"),

    # the following are critical mutations in FPs
    ("Y66 (EGFP)",                  "VTTLTYGVQC"),
    ("Y66W (ECFP)",                 "VTTLTWGVQC"),
    ("Y66H (EBFP)",                 "VTTLTHGVQC"),
    ("T203Y (EYFP)",                "DNHYLSYQSALSK"),
    ("Y145A,H148D (Cerulean)",      "LEYNANSDNV"),
    ("M153T,V163A,S175G (Venus)",   "YITADKQKNGIKANFKIRHNIEDGGVQL"),
    ("Q66M (mCherry)",              "FAWDILSPQFMYGSKAYV"),
    ("S62T,Q64N,Q66T (mStrawberry)","FAWDILTPNFTYGSKAYV"),
    ("Q66T (mOrange)",              "FAWDILSPQFTYGSKAYV"),
    ("Y67W (mHoneydew)",            "FAWDILSPQFMWGSKAYV"),
    ("Q66C (mTan/Ban)",             "FAWDILSPQFCYGSKAYV"),
    ("I197E (mBanana)",             "YIAGEKIDI"),
    ("I197 (mTangerine)",           "YKTDIKLDI"),
)

