# List of common protein tags

PROTEIN_TAGS = (
    ("FLAG","DYKDDDDK"),
    ("FLAG","DYKDHDI"),
    ("FLAG","DYKDHDG"),
    ("HA","YPYDVPDYA"),
    ("6xHIS","HHHHHH"),
    ("Myc","EQKLISEEDL"),
    ("TEV","ENLYFQG"),
    ("Myr","MGSNKSKPKDASQRR"),
    ("Myr","MGSSKSKPKDPSQRA"),
    ("V5","GKPIPNPLLGLDST"),
    ("S15","KETAAAKFERQHMDS"),
    ("Strep Tag","WSHPQFEK"),
    ("SBP Tag","MDEKTTGWRGGHVVEGLAGELEQLRARLEHHPQGQREP"),
    ("TAP","GRRIPGLINPWKRRWKKNFIAVSAANRFKKISSSGALDYDIPTTASENLYFQGEFGLAQHDEAVDNKFNKEQQNAFYEILHLPNLNEEQRNAFIQSLKDDPSQSANLLAEAKKLNDAQAPKVDNKFNKEQQNAFYEILHLPNLNEEQRNAFIQSLKDDPSQSANLLAEAKKLNDAQAPKVDANHQ"),
)

